### ISSUE TITLE
1.0 checklist

### ISSUE THREAD

**Issue by henryw374** [juxt/tick#135]
- [ ] revive or remove the deprecated namespaces
- [ ] fill in all empty sections of the documentation
- [ ] fix all the easy issues
- [ ] new `tick.api` ns

**Comment by henryw374** [comment]
2 remaining items:

- docs. can be improved as and when required
- intervals. nothing to say this will ever be revisited - so shouldn't block 1.0
